Adoptions domain
iesalonsodemadrigal/android-huellas pull request #15
Opened 2023-01-11 17:46 UTC by RafaX8

## Description de la tarea

Se desea visualizar un listado de animales para adoptar. Este listado puede tener distintos tipos de animales.

Por cada uno de los animales que se muestran guardamos: nombre, descripción, raza, sexo, fecha_nacimiento, tamaño, photo, tipo (perro, gato, etc.)

## ¿Cómo se ha implementado?

Se ha creado el apartado de domain de la feature adoptions con los siguientes archivos:
- Models.kt: Fichero que recoge las data class de dominio con las que trabajará adoptions --> Animal.

- Repositories.kt: Fichero que recoge las interfaces con las funciones con las que se trabajarán las data class --> AnimalRepository.
Se ha creado getAll() como una función suspendida que retorna un Either-> Error o una lista de Animal.

- GetAllUseCase: Clase con el caso de uso de la funcion getAll() del repositorio de AnimalRepository..

## Keywords

Domain, data class, repositories, Hilt, Either.

## Screenshots or Video

## Objetivos

## Criterios de Evaluación

2023-01-12 11:04 UTC, MiM14 submitted a review, later dismissed
🚀

2023-01-12 11:04 UTC, MiM14 commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/domain/GetAllAnimalsUseCase.kt
> +import com.iesam.proyecto_huellas.app.domain.functional.right
este import no te hace falta

2023-01-12 11:50 UTC, josem-perram requested changes
He dejado sugerencias :)

2023-01-12 11:50 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/domain/GetAllAnimalsUseCase.kt
> +    ) {
Formatea correctamente el código please.

2023-01-12 11:50 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/domain/Models.kt
> +data class Type(
Type puede ser muy general, yo pondría AnimalType

2023-01-12 11:57 UTC, josem-perram requested changes
Rafa, te he dejado unos comentarios y ademas, debes completar la info de la PR> reviewers, owner, project.... te puedes fijar en la PR que tiene Joel abierta. Gracias.

2023-01-12 14:39 UTC, RafaX8 commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/domain/GetAllAnimalsUseCase.kt
> +import com.iesam.proyecto_huellas.app.domain.functional.right
quitado :)

2023-01-13 10:20 UTC, alonsogallego7 approved these changes
Perfecto

2023-01-13 12:02 UTC, merged