Help alta como socio domain
iesalonsodemadrigal/android-huellas pull request #16
Opened 2023-01-11 18:00 UTC by Joelgh1

## Description de la tarea

Crear la capa de dominio para dar de alta socios

## ¿Cómo se ha implementado?

El modelo de datos está definido en el caso de uso porque solo debería servir para recoger la información que se enviará en un objeto.
El caso de uso recibirá el modelo ya creado como parámetro y lo pasará al repositorio directamente.
La función es suspendida porque tendrá que ejecutarse desde una corrutina al tener que enviar información a la api.

## Keywords

domain, use case, repository, hilt

## Screenshots or Video

## Objetivos

## Criterios de Evaluación

2023-01-12 09:36 UTC, DavidCaidas submitted a review, later dismissed
![zoolanda](https://user-images.githubusercontent.com/104197044/212031300-1caddc98-8677-4285-84b0-3cb2ccfab577.jpg)
fresh el code

2023-01-12 11:54 UTC, josem-perram requested changes
Dos cosillas:
1. Debes completar la información de la PR que aparece a la derecha: reviewers, owner, project, label... Te la he dejado completada para próximas PRs.
2. Un comentario sobre naming.

2023-01-12 11:54 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/help/domain/PartnerRepository.kt
> +    suspend fun submitPartnerData(partnerData: SubmitPartnerDataUseCase.PartnerInputModel)
@Joelgh1 mejor que submit, vamos a usar "savePartner" lo que estamos haciendo es almacenar la información, en esta ocasión lo almacenamos en una base de datos distribuida, ubicada en un servidor. Podemos obviar el sufijo Data.

2023-01-12 14:30 UTC, dherranz1 submitted a review, later dismissed
:+1:

2023-01-13 12:40 UTC, josem-perram requested changes
Please, revisa los comentarios.

2023-01-13 12:40 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/help/domain/SavePartnerUseCase.kt
> +    suspend operator fun invoke(partner: PartnerInputModel){
@Joelgh1 vamos a poner que esta función va a devolver un Either<ErrorApp, Boolean> donde el booleano me indica si se ha completado la acción con éxito o con error.

2023-01-13 14:29 UTC, Joelgh1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/help/domain/SavePartnerUseCase.kt
> +    suspend operator fun invoke(partner: PartnerInputModel){
Ya hice el cambio

2023-01-13 15:17 UTC, DavidCaidas approved these changes
se ve bien, si ya hiciste los cambios no se te olvide darle a resolve conversation

2023-01-15 23:50 UTC, dherranz1 approved these changes

2023-01-17 01:16 UTC, josem-perram approved these changes
👍

2023-01-17 14:20 UTC, merged