Issue 5 - Listado de noticias (Domain)
iesalonsodemadrigal/android-huellas pull request #17
Opened 2023-01-12 14:05 UTC by dherranz1

## Description de la tarea

Se desea visualizar los eventos que organiza la protectora. De cada uno de las noticias cuenta con la siguiente información: id, titulo, descripción, y url de la imagen.

## ¿Cómo se ha implementado?

- Definición del modelo de datos de dominio "New"
- Se define la interfaz del repositorio de noticias "NewsRepository"
- Se crea el caso de uso "GetNewsUseCase", dicha clase tiene un modelo de datos interno "NewFeed" que será el que se devuelva a la capa de presentación.
- Se hace uso de Either y ErrorApp para gestionar los errores/excepciones.
- Se hace uso del inyector de dependencias
- También se deja preparado para el uso de corrutinas

## Keywords

- Either
- Hilt
- ErrorApp
- Domain
- Coroutines

## Screenshots or Video

## Objetivos

## Criterios de Evaluación

2023-01-12 14:45 UTC, alonsogallego7 requested changes
Revisa los comentarios :)

2023-01-12 15:00 UTC, dherranz1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/domain/GetNewsUseCase.kt
> +    )
Ya, la idea de hacerlo es por buena práctica, para evitar propagar el modelo de dominio a la vista. Si posteriormente cambia el modelo de dominio y se le agregasen atributos que la vista no necesita, la vista tendría acceso a atributos que no debería.

2023-01-13 10:25 UTC, alonsogallego7 commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/domain/GetNewsUseCase.kt
> +    )
Entiendo 👍.

2023-01-13 10:25 UTC, alonsogallego7 approved these changes

2023-01-13 12:43 UTC, josem-perram approved these changes
👍

2023-01-13 12:43 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/domain/GetNewsUseCase.kt
> +    suspend operator fun invoke(): Either<ErrorApp, List<NewFeed>> {
Cosas de namings, noticias es news, si pones new es como siera nuevo. Fíjate que NewFeed es lo mismo que News, entonces, no haría falta NewFeed, devolvemos directamente News.

2023-01-13 12:43 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/domain/GetNewsUseCase.kt
> +    )
vaya, me adelanté. Van a cambiar cosas, pero hay que estar abiertos a las dos posibilidades, a devolver News o a devolver NewsFeed. En este caso, te aceptamos tu propuesta.

2023-01-13 12:53 UTC, merged