Adoptions data
iesalonsodemadrigal/android-huellas pull request #19
Opened 2023-01-12 18:39 UTC by RafaX8

Pendiente de crear

2023-01-13 09:23 UTC, Joelgh1 commented on app/src/main/java/com/iesam/proyecto_huellas/app/data/remote/ApiClient.kt
> +class ApiClient @Inject constructor() {
El apiClient no tiene dependencias por lo que este inject no tiene ningún sentido

2023-01-13 09:26 UTC, Joelgh1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/data/AnimalDataRepository.kt
> +        val animals:List<Animal>
Para que puedas cambiar el contenido de la variable debes usar var en lugar de val

2023-01-13 09:31 UTC, Joelgh1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/data/local/AnimalLocalDataSource.kt
> +interface AnimalLocalDataSource {
Yo lo llamaría AnimalLocalSource

2023-01-13 09:36 UTC, Joelgh1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/data/remote/AnimalRemoteDataSource.kt
> +interface AnimalRemoteDataSource {
Lo mismo que en la interfaz de local, yo quitaría lo de Data y lo llamaría AnimalRemoteSource

2023-01-13 09:39 UTC, Joelgh1 requested changes
Revisa los comentarios

2023-01-13 10:00 UTC, RafaX8 commented on app/src/main/java/com/iesam/proyecto_huellas/app/data/remote/ApiClient.kt
> +class ApiClient @Inject constructor() {
Está bien saberlo, gracias 😅

2023-01-13 10:04 UTC, RafaX8 commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/data/AnimalDataRepository.kt
> +        val animals:List<Animal>
No hay problema, porque ahí no se encuentra inicializada todavía y solo se inicializa cuando decide recoger de remoto o de local, una única vez en la función, no se cambia más el valor. Lo hablamos en clase y decidimos si cambiarlo a var. 🤔

2023-01-13 10:24 UTC, Joelgh1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/data/AnimalDataRepository.kt
> +        val animals:List<Animal>
Tienes razón no me había dado cuenta

2023-01-13 15:10 UTC, Joelgh1 submitted a review, later dismissed
Todo ok

2023-01-13 15:51 UTC, josem-perram requested changes
REvisa los comentarios please.

2023-01-13 15:51 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/app/data/di/LocalDataModule.kt
> +    fun provideAnimalDao(appDatabase: AppDatabase): AnimalDao {
Este debería ir en la feature correspondiente.

2023-01-13 15:51 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/app/data/di/RemoteDataModule.kt
> +    fun provideApiClient() : ApiClient{
Esto veremos como mejorarlo

2023-01-13 15:51 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/data/local/AnimalLocalDataSource.kt
> +interface AnimalLocalDataSource {
![image](https://user-images.githubusercontent.com/93087250/212360448-81901874-2c34-4e65-9799-c30b7437d004.png)

2023-01-13 15:51 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/data/local/db/AnimalDbLocalDataSource.kt
> +            ErrorApp.DataError().left()
Si está vacío, debemos contemplarlo como nulo, no como un error.

2023-01-13 15:51 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/data/local/db/AnimalDbLocalDataSource.kt
> +                ErrorApp.DataError().left()
Lo mismo, deberíamos devolver nulo.

2023-01-13 15:51 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/data/local/db/AnimalEntity.kt
> +    val type: AnimalTypeEntity,
Genial! el @Embedded

2023-01-13 15:51 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/data/remote/api/AnimalApiRemoteDataSource.kt
> +            val animals = apiClient.getAnimals()
Lo puedes meter en una única línea:

```
apiClient.getAnimals().map{   }.right()
```

2023-01-13 15:51 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/domain/GetAllAnimalsUseCase.kt
> -        return animalRepository.getAll()
por qué has quitado esta línea?? aquí no hace falta validar error - success, está mejor con lo que has quitado
 return animalRepository.getAll()

2023-01-13 15:59 UTC, RafaX8 commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/data/remote/api/AnimalApiRemoteDataSource.kt
> +            val animals = apiClient.getAnimals()
okay 👍

2023-01-16 15:58 UTC, albertoag128 commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/data/remote/AnimalRemoteDataSource.kt
> +interface AnimalRemoteDataSource {
Yo no estoy de acuerdo Joel, no habiamos establecido una nomenclatura mediante la cual nombrabamos a las clases con El nombre del modelo + Local/Remote + Data + Source

2023-01-16 15:59 UTC, albertoag128 submitted a review, later dismissed
En lineas generales esta todo bien. Buen trabajo!!

2023-01-16 17:12 UTC, RafaX8 commented on app/src/main/java/com/iesam/proyecto_huellas/app/data/remote/ApiEndPoints.kt
> +    fun getAllAnimals(): retrofit2.Call<List<AnimalApiModel>>
Pues chequeando por internet, es bastante probable que tengas razón. Igualmente le preguntaré a Chema, pero podría cambiarlo no problem 👍

2023-01-17 01:19 UTC, josem-perram approved these changes
@RafaX8 Está genial Rafa, yo lo veo muy bien como lo tienes. Hay cosas del ApiClient que cambiaremos más adelante pero por lo demás, está ok.

2023-01-17 15:36 UTC, RafaX8 commented
Ha habido muchos cambios. En resumen, se ha refactorizado buena parte del proyecto y se han creado componentes y módulos para la correcta utilización de hilt, room, retrofit, etc.

2023-01-17 18:35 UTC, Joelgh1 submitted a review, later dismissed
Revisa los comentarios

2023-01-17 18:35 UTC, Joelgh1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/data/remote/api/AnimalApiRemoteDataSource.kt
> +class AnimalApiRemoteDataSource @Inject constructor(private val apiClient: ApiEndPoints) :
Falta implementar la función genérica que usaremos para las respuestas de retrofit

2023-01-17 18:35 UTC, Joelgh1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/data/remote/api/ApiEndPoints.kt
> +    fun getAllAnimals(): retrofit2.Call<List<AnimalApiModel>>
Tendrás que cambiar la función para que sea suspendida y que devuelva Response una vez que tengas la nueva implementación

2023-01-17 19:07 UTC, josem-perram approved these changes
👍

2023-01-18 10:17 UTC, albertoag128 commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/data/remote/api/ApiEndPoints.kt
> +    fun getAllAnimals(): retrofit2.Call<List<AnimalApiModel>>
Lo mismo que dice Joel, creo que al utilizar corrutinas cambiamos el Call a un Response

2023-01-18 10:22 UTC, albertoag128 commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/data/remote/AnimalRemoteDataSource.kt
> +interface AnimalRemoteDataSource {
Una pregunta: esto no debería de llamarse AnimalRemoteDataRepository? Lo pregunto por el tema de que normalmente los repositorios son interfaces con metodos sin body que serán implementados por otros archivos (abstracciones), y los sources o fuentes de datos, son aquellos archivos que si devuelven datos (concrecciones)

2023-01-18 10:39 UTC, albertoag128 approved these changes
En lineas generales es una buena pr Rafa!! Solo una cosilla:
-No se si utilizando corrutinas en api el hecho de poner Call en vez de Response es una agravante que puede afectar a la ejecución del programa. Yo personalmente creo que no, creo que es algo que se debe cambiar pero tampoco quiero que genereis mucha deuda técnica por tanto daré el approve.

2023-01-18 10:48 UTC, RafaX8 commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/data/remote/api/ApiEndPoints.kt
> +    fun getAllAnimals(): retrofit2.Call<List<AnimalApiModel>>
Así es

2023-01-18 10:50 UTC, RafaX8 commented
> En lineas generales es una buena pr Rafa!! Solo una cosilla: -No se si utilizando corrutinas en api el hecho de poner Call en vez de Response es una agravante que puede afectar a la ejecución del programa. Yo personalmente creo que no, creo que es algo que se debe cambiar pero tampoco quiero que genereis mucha deuda técnica por tanto daré el approve.

Efectivamente, Alberto, pero se me escapó mientras hacía esta rama. Ahora estoy esperando a Joel para poder hacer merge con su código, que él ya lo ha implementado. Lo cambiaremos lo más rápido posible. 👍

2023-01-20 15:40 UTC, merged