Help alta como socio data
iesalonsodemadrigal/android-huellas pull request #20
Opened 2023-01-13 15:33 UTC by Joelgh1

## Description de la tarea

Crear la capa de datos para dar de alta socios

## ¿Cómo se ha implementado?

El repositorio le pasa el modelo de dominio que contiene los datos del socio al remote source, que lo convierte a un api model y se lo envía al api client para que haga el post de los datos.
Si el post es correcto se devuelve un true y en caso de que se produzca un error se devolverá un errorApp.
El api model contiene los mismos datos que el modelo de dominio.
El HelpModule contiene los binds para que el inyector de dependencias sepa que concreción se va a utilizar de las interfaces del repositorio y el remote source.

## Keywords

retrofit, post, remote, either

## Screenshots or Video

## Objetivos

## Criterios de Evaluación

2023-01-13 15:42 UTC, albertoag128 submitted a review, later dismissed
Hasta ahora no habia trabajado con el @POST de retrofit, aunque para corregir esta pr le he echado un vistazo y creo que está todo bien. Entiendo que tampoco se puede probar ahora mismo dado que la bd aún no está confeccionada.

2023-01-13 16:20 UTC, RafaX8 approved these changes
🚀
![image](https://user-images.githubusercontent.com/104196849/212368394-ae9cde49-8964-454e-9921-100cd1bb91d6.png)

2023-01-17 01:20 UTC, josem-perram requested changes
@Joelgh1 Creo que es buen momento para que añadas las clases genéricas para remote en esta PR.

2023-01-17 01:20 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/app/data/remote/ApiClient.kt
>  class ApiClient {
Deberías cambiar el ApiClient con las clases que os he dado para añadirlo con Hilt.

2023-01-17 16:36 UTC, RafaX8 approved these changes
🚀
![image](https://user-images.githubusercontent.com/104196849/212957935-1ff813d9-0e0f-4622-b6c0-2ff42188d5e1.png)

2023-01-17 17:33 UTC, albertoag128 approved these changes
Veo que ya se han implementado clases genericas para llamar al ApiClient asi como los archivos necesarios para Hilt. Que yo vea esta todo bien, buen trabajo!!

2023-01-18 23:40 UTC, josem-perram approved these changes
Genial!

2023-01-19 09:16 UTC, merged