6 news listado de noticias (data)
iesalonsodemadrigal/android-huellas pull request #21
Opened 2023-01-17 12:16 UTC by dherranz1

## Description de la tarea

Se desea gestionar la información de las noticias de la protectora. Para no estar continuamente descargando las noticias, se desarrollará una gestión de datos local.
La caché que se quiere implementar es la siguiente: Si existen datos locales y la información se ha obtenido hace 1h, se devuelve, si tienen más de 1h o no existen, se descargan de la API.

## ¿Cómo se ha implementado?

Definición de las interfaces NewsLocalDataSource y NewsRemoteDataSource

Se implementa toda la estructura correspondiente a Room (Dao, RoomDataBase, Entities...), mappers y la concreción NewsRoomDbLocalDataSource.

Por otra parte, retrofit para remoto. Definición de la interfaz de retrofit propia para las noticias, modelos de api, mapper, concreción NewsApiRemoteDataSource.

Se crea el repositorio de datos NewsDataRepository que tiene la siguiente lógica: Lee de local y si recibe error, propaga un error, si recibe una lista vacía se asume que no hay datos o estos han caducado y se buscan en remoto.

Para la implementación de la caché se llega al siguiente convenio: se realiza en la propia implementación NewsRoomDbLocalDataSource. Almacena, dentro de la propia entity, el tiempo del reloj del sistema la última vez que ha guardado los datos. Cuando se le soliciten los datos, este comprobará si se ha pasado el tiempo límite de vida de la caché, devolviendo una lista vacía en dicho caso.

Se agrega el inyector de dependencias hilt para evitar el uso de una clase factory.

## Disclaimer

Pendiente: separar la clase AppDataBase para cada feature y unificar clases comunes

## Keywords

- Retrofit
- Room
- Hilt
- Inyector de dependencias
- Caché

## Screenshots or Video

Se comprueba cómo funciona caché, en primer lugar se detecta que está desactualizado, inmediatamente se hace una nueva ejecución y ya no se muestra el mensaje, por tanto lo coge de local. Tras esperar un tiempo de prueba para que caduque, vuelve a salir el mensaje de desactualizado.

![prListadoNoticias](https://user-images.githubusercontent.com/114154511/212891668-2edde110-e198-4620-9b04-527ace5e4e3c.png)

## Objetivos

## Criterios de Evaluación

2023-01-17 15:21 UTC, Joelgh1 commented on app/src/main/java/com/iesam/proyecto_huellas/app/data/remote/ApiClient.kt
>  class ApiClient {
Esto falta borrarlo

2023-01-17 15:22 UTC, Joelgh1 commented on app/src/main/java/com/iesam/proyecto_huellas/app/data/remote/ApiEndPoints.kt
Tambien borrar

2023-01-17 15:24 UTC, Joelgh1 commented on app/src/main/java/com/iesam/proyecto_huellas/app/di/RemoteDataModule.kt
> +@InstallIn(SingletonComponent::class)
Se actualizara con mis cambios

2023-01-17 15:34 UTC, Joelgh1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/data/remote/retrofit/NewsApiRemoteDataSource.kt
> +    override suspend fun getNews(): Either<ErrorApp, List<New>> {
Habra que hacer cambios cuando actualices la implementacion de retrofit

2023-01-17 15:35 UTC, Joelgh1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/data/remote/retrofit/NewsApiEndPoints.kt
> +    fun getNews() : Call<List<RetrofitNew>>
Cambiar a suspend y devolver response

2023-01-17 15:36 UTC, Joelgh1 requested changes
Revisa los comentarios

2023-01-17 15:47 UTC, MiM14 requested changes
Cuando realices los cambios que necesites vuelve a pedirme review

2023-01-18 09:26 UTC, dherranz1 commented on app/src/main/java/com/iesam/proyecto_huellas/app/data/remote/ApiClient.kt
>  class ApiClient {
Hecho

2023-01-18 09:27 UTC, dherranz1 commented on app/src/main/java/com/iesam/proyecto_huellas/app/data/remote/ApiEndPoints.kt
Hecho

2023-01-18 09:27 UTC, dherranz1 commented on app/src/main/java/com/iesam/proyecto_huellas/app/di/LocalDataModule.kt
> +    fun provideNewsDao(appDatabase: AppDatabase) : NewsDao{
Hecho

2023-01-18 09:28 UTC, dherranz1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/data/remote/retrofit/NewsApiEndPoints.kt
> +    fun getNews() : Call<List<RetrofitNew>>
Hecho

2023-01-18 10:35 UTC, dherranz1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/data/remote/retrofit/NewsApiRemoteDataSource.kt
> +    override suspend fun getNews(): Either<ErrorApp, List<New>> {
Propuesta de código agregada como un comentario tal como hemos acordado, conservando mientras tanto el código funcional hasta poder hacer el cambio y probarse.

2023-01-18 15:04 UTC, Joelgh1 approved these changes
Se ve fresco

2023-01-18 18:36 UTC, MiM14 approved these changes
Te he dejado un comentario, pero buen trabajo con esta PR 👌

2023-01-18 18:36 UTC, MiM14 commented on app/src/main/java/com/iesam/proyecto_huellas/MainActivity.kt
> +import kotlinx.coroutines.launch
Cuidado con los importes que utilizas para probar cosas

2023-01-18 18:36 UTC, MiM14 commented on app/src/main/java/com/iesam/proyecto_huellas/app/di/RemoteDataModule.kt
> +@InstallIn(SingletonComponent::class)
👌

2023-01-18 23:47 UTC, josem-perram requested changes
Daniel, en la PR hay problemas comunes a otros tickets de tus compañeros pero lo has resuelto de manera diferente. Por favor, habla con los compañeros para estar alineados y que te enseñen sus propuestas.

2023-01-18 23:47 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/data/NewsDataRepository.kt
> +        var error = false
Hola Daniel, no entiendo por qué usas un flag para gestionar los errores, creo que no es necesario, please, habla con tus compañeros porque han solucionado este problema sin usar flags.

2023-01-18 23:47 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/data/local/db/room/NewsRoomDbLocalDataSource.kt
> +        val cache = newsDao.getNews()
otra vez obtienes noticias?? Esto no es nada eficiente y además puede generar errores. Consultas las noticias dos veces, una en la caché y otra para recuperarlas. Por favor, habla con tus compañeros para alinearos en la solución de este problema.

2023-01-18 23:47 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/domain/GetNewsUseCase.kt
> +        return if(result.isLeft())
Esto no debería estar en esta PR, si es de la capa de datos pero se hizo en la PR de dominio, por qué está aquí?

Además te comento que no es necesario tratar el error (isLeft) cuando vuelves a generar el mismo error (ErrorApp.DataError().left). Please, coméntalo con tus compañeros para estar alineados.

2023-01-19 00:18 UTC, dherranz1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/domain/GetNewsUseCase.kt
> +        return if(result.isLeft())
Esto lo vi en el momento de hacer la pr y no entiendo qué ha sucedido porque arrastré los cambios de la rama develop tras hacer los merges, tanto mis compañeros como yo... y no sé por qué me sale como que es nuevo si la estoy comparando con la propia rama develop....

2023-01-19 00:24 UTC, dherranz1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/data/local/db/room/NewsRoomDbLocalDataSource.kt
> +        val cache = newsDao.getNews()
Sí, basta con pasarlo como parámetro, pero no me di cuenta de cambiarlo tras probarlo. Lo consulto con el equipo a ver en qué diferimos.

2023-01-19 00:33 UTC, dherranz1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/data/NewsDataRepository.kt
> +        var error = false
Se puede escribir de otros modos pero en ese momento lo más rápido que me salía era esa forma para evitar poner diversos return iguales y así tener un único punto de salida. Lo cambiaré con más tranquilidad a un estilo más kotlin.

2023-01-21 23:01 UTC, josem-perram requested changes
@dherranz1 te he puesto algunas mejoras. La de varargs la he puesto de memoria pero creo que podría funcionar. El gran beneficio de eso es usar @Transactions.

2023-01-21 23:01 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/data/local/db/room/NewsRoomDbLocalDataSource.kt
> +                newsDao.saveNews(news.toEntity(time))
Creo que es más eficiente tener un:
```
   @Insert(onConflict = OnConflictStrategy.REPLACE)
    @Transaction
    fun saveNews(vararg news : NewsEntity)
```
Con @Transaction evitamos cualquier inconsistencia en la caché al insertar varios elementos y con vararg podemos insertar más de uno.
```
*(newsList.map{ it.toEntity(time) }).toTypedArray()
```

2023-01-22 13:21 UTC, dherranz1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/data/local/db/room/NewsDao.kt
> +    @Query("DELETE FROM $TABLA_NAME_NEWS")
Lo cambio en un momento, en otras ocasiones lo he empleado y es más cómodo y simple la verdad.

2023-01-22 13:22 UTC, dherranz1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/data/NewsDataRepository.kt
> +
Intentaré coger la costumbre de darle a reformatear

2023-01-22 13:23 UTC, dherranz1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/data/local/db/room/NewsRoomDbLocalDataSource.kt
> +            ErrorApp.DataError().left()
Le echo un ojo y hago el cambio

2023-01-22 13:41 UTC, dherranz1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/data/local/db/room/NewsRoomDbLocalDataSource.kt
> +                newsDao.saveNews(news.toEntity(time))
@josem-perram Vale, lo puedo cambiar sin problema. No sé si estaré equivocado pero creo que podrían darse situaciones donde sea problemático usar la transacción, al menos tal como creo que está planteado. Me explico, entiendo que son datos que no controlamos y que pueden llegar a generar un error que no se ha previsto. Ejemplo, si tras recoger los datos de la web ajena, se topa con un dato que origina un error en la transacción... La transacción hace un rollback y no se inserta nada. Previamente a la inserción se da por hecho que ha habido una limpieza de la tabla y no hay registros. Si esto fuera un error puntual se volvería a pedir la información y no pasaría nada pero, si es un error persistente nos quedaríamos sin datos.

En relación a lo anterior, usando la transacción, entiendo que se debería agrupar junto a la sentencia de borrado. Así, en caso de fallar, que no se quede sin caché local. En algunos casos no interesará tener cierta información posiblemente desactualizada, pero en otros seguramente sea más relevante conservarlo.

Si no se usa la transacción, al menos, obtendríamos datos hasta el elemento que ocasiona el fallo y la aplicación podría trabajar con algunos elementos, aunque no tenga todos. Incluso ese elemento que falla se podría ignorar y continuar.

¿Qué sería más recomendable para el contexto de uso que se va a dar a la app?

2023-01-22 15:02 UTC, dherranz1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/data/local/db/room/NewsDao.kt
> +    @Query("DELETE FROM $TABLA_NAME_NEWS")
@josem-perram Siempre lo he usado para eliminar elementos concretos, sin embargo para este caso, tras consultar la documentación, no he visto una forma diferente de eliminar todos los datos de la tabla que no sea pasando los elementos que se desean borrar (sea un único elemento o un listado). Entonces, no sé si habrá una manera simple de borrar toda la tabla con @delete sin pasarle los elementos.

¿Hay alguna forma más sencilla? Porque si sólo es así... Tendría que hacer una consulta que no necesito hacer  empleando la sentencia sql...

2023-01-24 10:29 UTC, josem-perram requested changes
@dherranz1  sólo tendrías que mirar lo que comento del save. Es importante entender por qué necesitamos transacción en la caché. Cualquier duda me dices.

2023-01-24 10:29 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/data/local/db/room/NewsDao.kt
> +    @Query("DELETE FROM $TABLA_NAME_NEWS")
Error mio, quieres vaciar la tabla, está bien lo que propones.

2023-01-24 10:29 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/data/local/db/room/NewsRoomDbLocalDataSource.kt
> +            ErrorApp.DataError().left()
No hace falta realizar cambio, lo vemos más adelante

2023-01-24 10:29 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/data/local/db/room/NewsRoomDbLocalDataSource.kt
> +                newsDao.saveNews(news.toEntity(time))
El problema de no usar transacción es que de 10 elementos, al insertar el 5º (por ejemplo) puede darse un error. Si tienes transacción, la tabla estará vacía por lo que en la próxima consulta, volverá a ir a red. Si inserta sólo los 4 primeros, la tabla tiene datos por lo que la caché entrará en juego y estamos usando una caché con datos incompletos y no podremos ir a red hasta que caduquen.

2023-01-25 15:45 UTC, MiM14 approved these changes
Lo veo bien, lo único es mencionarte con nosotros en YouthCard planteamos no usar either en local debido a que room no devuelve nulos. Espero poder compartir nuestras opiniones con una charla.

2023-01-25 15:52 UTC, Joelgh1 approved these changes

2023-01-25 20:20 UTC, MiM14 submitted a review, later dismissed

2023-01-26 00:00 UTC, josem-perram approved these changes
Daniel, please, revisa los dos comentarios.

2023-01-26 00:00 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/data/NewsDataRepository.kt
> +        if (news.get().isEmpty()) {
@dherranz1 vamos a analizar este código. 
```
var news = newsLocalDataSource.getNews()
```
news es un Either<ErrorApp, List<New>>. Esto significa que tiene un sólo valor, en la derecha (List<News>) o en la izquierda (ErrorApp). NO tiene ambos valores.

Si tu haces un ``news.get()`` lo que estás haciendo es obtener el valor de la derecha, en este caso un List<News>. Y ahora te pregunto, que pasa si la función lo que te ha devuelto es un ErrorApp (izquierda) ?? pues estarías haciendo un get() de la parte izquierda, y si revisas el código que tiene Either puedes ver que tiene lo siguiente:
```
    data class Left<out T>(val value: T) : Either<T, Nothing>() {
        override fun isRight(): Boolean = false
        override fun isLeft(): Boolean = true
        **override fun get(): Nothing = throw NoSuchElementException("Either.Right.value on Left")**
    }
```
Esto quiere decir, que tu aplicación va a fallar, va a crashear porque la parte izquierda no devuelve nada, y lanza una excepción.

Si tu función `` newsLocalDataSource.getNews() `` devuelve  un either, antes tienes que hacer una condición:
if (news.isLeft()){ .... } así nos aseguramos que si tenemos un ErrorApp entonces tenemos que ir a red. Peeeeeero además vamos a red si es Right y lo devuelto es un listado vacío, así que la condición completa sería:
```
if (news.isLeft() || news.get().isEmpty()){
....
```
Fíjate que es muy importante que preguntes primero si es Left, porque si lo es, ya no valida la segunda condición y entra en la iteración del if. Si es right, entonces es seguro poder hacer news.get().isEmpty.

Espero haberte ayudado, veremos esto mañana con los compañeros de clase.

2023-01-26 00:00 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/data/remote/retrofit/NewsApiRemoteDataSource.kt
> +            if (response.isSuccessful){
@dherranz1 no ibas a cambiar esto aquí ??

2023-01-26 00:01 UTC, josem-perram requested changes
Perdón, te dí el approve pero hay que corregir cosas, revisa mis comentarios.

2023-01-26 07:26 UTC, dherranz1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/data/NewsDataRepository.kt
> +        if (news.get().isEmpty()) {
Hecho

2023-01-26 07:26 UTC, dherranz1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/data/remote/retrofit/NewsApiRemoteDataSource.kt
> +            if (response.isSuccessful){
Hecho

2023-01-26 09:20 UTC, Joelgh1 approved these changes

2023-01-26 14:45 UTC, josem-perram approved these changes
🚀

2023-01-26 14:47 UTC, merged