Lista de Alertas (Data)
iesalonsodemadrigal/android-huellas pull request #22
Opened 2023-01-17 22:26 UTC by alonsogallego7

## Description de la tarea

Se pide desarrollar la lógica para que si existen alertas en local y hayan sido descargadas hace 1 minuto, se devuelvan estas pero, si no existen o hayan sido descargadas hace más de 1 minuto, se obtengan de red.

## ¿Cómo se ha implementado?

Se han implementado las siguientes fuentes de datos:

- Room (local)

- - Dao: Contiene las funciones que va a utilizar la base de datos para devolver o guardar alertas.
- - Entity: Entidad "alerta" en la base de datos.
- - DbLocalMapper: Transforma un modelo de entidad en uno de dominio y al revés. En el segundo caso, se añade una variable que almacena la fecha/hora actual.
- - DbLocalData: Implementa los métodos para obtener y guardar alertas de la base de datos, llamando a los métodos de la DAO. Para que se obtengan de red las alertas si no existen o han sido descargadas hace 1 minuto se realiza lo siguiente: Se le suma 1 minuto a la hora en la que haya sido guardada la alerta y, cuando sea mayor a la hora actual, se obtendrá de nuevo desde red.

- Api (remoto)

- - ApiEndPoints: Contiene el método para obtener una lista de alertas de la API.
- - ApiModel: Modelo de lo que vamos a recoger de red.
- - ApiMapper: Transforma un ApiModel en un modelo de dominio.
- - ApiRemoteData: Sus métodos llaman al ApiEndPoints para que obtenga las alertas para después transformarlas al modelo de dominio.

Se ha introducido Hilt para agilizar la inserción de dependencias.

## Keywords

Room, Dao, Entity, Api, Retrofit, Hilt, Either.

## Objetivos

## Criterios de Evaluación

2023-01-18 10:32 UTC, RafaX8 commented on app/src/main/java/com/iesam/proyecto_huellas/MainActivity.kt
> +import javax.inject.Inject
No tendrías que haber subido nada de MainActivity, pero bueno, entiendo que se te haya colado. Antes de hacer merge, actualiza la rama quitando estos imports, porfa :)

2023-01-18 10:47 UTC, RafaX8 approved these changes
Está fino, solo falta esperar a que Joel haga su merge. Lee el comentario que te puse porfi 🚀
![image](https://user-images.githubusercontent.com/104196849/213151988-5100d417-6816-481c-8dc0-38a5dd5819cf.png)

2023-01-18 23:54 UTC, josem-perram requested changes
Please, revisa comentarios.

2023-01-18 23:54 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/alerts/data/AlertDataRepository.kt
> +                    if (localSource.save(alerts).isLeft()) {
esto se puede obviar, realmente no haces nada aquí, sólo mostrar un log. Si falla local, no pasada nada, devuelves lo obtenido en remoto.

2023-01-18 23:54 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/alerts/data/AlertDataRepository.kt
> +        } catch (e: Exception) {
Esto no debería pasar, no podemos "camuflar" las excepciones.

2023-01-18 23:54 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/alerts/data/local/db/AlertDao.kt
> +    @Query("DELETE FROM $TABLE_NAME_ALERT")
Hay una anotación para esto @delete

2023-01-18 23:54 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/alerts/data/remote/api/AlertApiRemoteDataSource.kt
> +        } catch (e: Exception) {
Esto no es necesario, el try catch.

2023-01-18 23:54 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/alerts/data/remote/api/AlertApiRemoteDataSource.kt
> +        if(response.isSuccessful) {
Esta función sobra.

2023-01-18 23:54 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/alerts/data/remote/api/AlertApiRemoteDataSource.kt
> +    override suspend fun getAll(): Either<ErrorApp, List<AlertModel>> {
el naming getAll es confuso, mejor geAlerts

2023-01-20 15:39 UTC, josem-perram requested changes
Hola Alonso, por favor, revisa los comentarios. Hay cosas que me preocupan del código:
1. El camuflar los errores con try catch, no deberíamos hacerlo.
2. Hemos visto en clase cómo parsear remoto, sigues haciendolo como antes cuando ya se ha explicado como mejorar esto. Por favor, revisa con tus compañero.

2023-01-20 15:39 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/alerts/data/AlertDataRepository.kt
> +                    ErrorApp.DataError().left()
debemos devolver el error que nos da remoto.

2023-01-20 15:39 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/alerts/data/remote/api/AlertApiRemoteDataSource.kt
> +        val response = apiServices.getAllAlerts()
POr qué haces esto? ya hemos visto en clase que esto ya no lo hacemos, por favor, habla con tus compañeros.

2023-01-24 10:33 UTC, josem-perram requested changes
Alonso, te he dejado un par de comentarios. Uno importante sobre el tema de no propagar el left que viene de remoto. El otro es simplemente añadir una query que no recuerdo si lo tenías ya hecho así y te lo he hecho cambiar 🙏

2023-01-24 10:33 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/alerts/data/AlertDataRepository.kt
> +                ErrorApp.DataError.left()
Alonso, debemos devolver el error que recibimos de remoto, no tenemos que crear un nuevo error. Si no queda claro lo vemos esta tarde.

2023-01-24 10:33 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/alerts/data/local/db/AlertDao.kt
> +    @Delete
Perdona, aquí debes vaciar la tabla al completo, quizás te toque hacer una query al completo:
``@Query("DELETE FROM $nombre_tabla")`` Creo que sobre esto te dí información errónea. Mis disculpas.

2023-01-24 23:01 UTC, josem-perram submitted a review, later dismissed
Bien Alonso, vamos a por otro ticket 🚀

2023-01-25 14:20 UTC, RafaX8 commented on app/src/main/java/com/iesam/proyecto_huellas/MainActivity.kt
>  import dagger.hilt.android.AndroidEntryPoint
Estos imports los puedes quitar, si se te cuelan haciendo pruebas 😅

2023-01-25 14:23 UTC, RafaX8 submitted a review, later dismissed
Perdón por tardar tanto con la Review. Está correcto 🚀

2023-01-26 14:42 UTC, RafaX8 approved these changes
fino 🚀
![image](https://user-images.githubusercontent.com/104196849/214864970-13a72201-eaf2-48a3-bacc-6dfd687c7c28.png)

2023-01-26 15:35 UTC, albertoh8 approved these changes
🚀Muy buena pr.

2023-01-26 15:37 UTC, merged