Listado de noticias (presentación)
iesalonsodemadrigal/android-huellas pull request #24
Opened 2023-01-19 10:20 UTC by dherranz1

## Description de la tarea

Se desea visualizar el listado de noticas, mostrando cada noticia con un cardview que, al tocar sobre la noticia, nos permita ver su descripción.

## ¿Cómo se ha implementado?

Se crea toda la estructura para seguir el patrón MVVM y las clases necesarias para manejar un listado con un recyclerview.

Para el recyclerview se crea el adapter y su viewholder (NewsFeedAdapter y NewsFeedViewHolder) y los layouts xml para la vista.

Por otra parte se crea el viewModel "NewsFeedViewModel" para obtener la información con live data desde el caso de uso.

Respecto al cardview de la vista se agrega una animación que permite desplegar el contenido de la notica haciendo una transición. Se omite dicha animación en el colapaso debido a un efecto negativo en la visualización.

## Disclaimer

Temporalmente se dan unas dimensiones provisionales para hacer las pruebas y poder visualizarlo de una forma aproximada a su aspecto final, en posteriores tickets se integrará un estilo común para todos

## Keywords

- MVVM
- CardView
- Transition Animation
- ViewModel
- Adapter
- RecyclerView
- Observer
- LiveData

## Screenshots or Video

[CardViewAnimation.webm](https://user-images.githubusercontent.com/114154511/213416657-5946f34d-70fd-48be-8590-fad0bd6fe28b.webm)

## Objetivos

## Criterios de Evaluación

2023-01-21 23:17 UTC, josem-perram requested changes
Daniel, revisa los comentarios please. Además, faltan muchas cosas por hacer, el loading, el diffutil para el recyclerview, márgenes...

2023-01-21 23:17 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/presentation/NewsFeedViewHolder.kt
> +        Glide.with(view.context).load(news.url).into(
Esto deberíamos sacarlo a una función de extensión, por favor revisa algunos de los proyectos hechos en clase.

2023-01-21 23:17 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/presentation/NewsFeedViewHolder.kt
> +        binding.titleNews.setOnClickListener { toggleDescriptionVisibility(binding) }
el setOnClickListener debe ir asociado al view que le pasas por constructor que es toda la vista. Ese view, lo recibe el padre y lo llama itemView o viewItem (no recuerdo), lo puedes poner ahí y así te coge toda la celda.

2023-01-21 23:17 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/presentation/NewsFeedViewHolder.kt
> +        binding.imageNews.setOnClickListener { toggleDescriptionVisibility(binding) }
Esto sobraría.

2023-01-21 23:17 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/presentation/NewsFeedViewHolder.kt
> +            binding.descriptionNews.visibility = View.GONE
Hay que meterle también una transición más lenta cuando se oculta.

2023-01-21 23:17 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/presentation/NewsFeedViewHolder.kt
> +        )
Recuerda, que hablemos sobre el reciclado de los items.

2023-01-21 23:17 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/presentation/NewsFeedViewModel.kt
> +        val newsFeed: Either<ErrorApp, List<GetNewsUseCase.NewFeed>>? = null
Ya te adelanto que necesitaremos un nuevo modelo llamado NewsUI que contendrá los datos que tiene NewFeed (recuerda que noticias en singular o plural news y que new es 'nuevo'). 

Este NewsUI saldrá de un map de NewFeed y tendrá los mismos atributos MÁS un atributo que se va a llamar isExpanded. Este atributo nos ayudará a saber si el item que estoy mostrando en el recyclerview está expandido o no. Recuerda que las vistas de los items se reciclan y esto significa que si el item1 está expandido cuando haga scroll y el item12 (me lo invento) use la vista reciclada del item1, aparecerá expandido y no debería ser así.

Lo que habría que hacer es que cuando se haga click sobre la card, hay que poner a true/false el atributo isExpanded y cada vez que pintemos la vista validar if (isExpanded) poner a Visible, sino poner a Gone. Esto se haría en el ViewHolder

2023-01-21 23:17 UTC, josem-perram commented on app/src/main/res/values/dimens.xml
> +    <dimen name="cvCornerRadius">8dp</dimen>
Daniel, no debemos usar cv, nunca debemos usar abreviaturas y para los dimens, se usa underscore. Por ejemplo:
<dimen name="card_corner_radius">8dp</dimen>
<dimen name="card_elevation">4dp<</dimen>
El margin no debemos declararlo así.

Esto lo tenemos que hablar en clase.

2023-01-22 20:18 UTC, dherranz1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/presentation/NewsFeedViewHolder.kt
> +        Glide.with(view.context).load(news.url).into(
Hecho

2023-01-22 20:23 UTC, dherranz1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/presentation/NewsFeedViewHolder.kt
> +        binding.titleNews.setOnClickListener { toggleDescriptionVisibility(binding) }
No sé si entiendo lo que quieres decir exactamente, los he agrupado y he asociado el click a ese grupo, de ese modo dejo fuera los botones de compartir y abrir en el navegador para evitar problemas.

2023-01-22 20:32 UTC, dherranz1 commented on app/src/main/res/values/dimens.xml
> +    <dimen name="cvCornerRadius">8dp</dimen>
Esto sólo era para poder hacer una visualización similar, que tuviera aspecto de cardview y hacer el vídeo, esto ya lo limpio para usar el estilo que se está haciendo del nuevo ticket cuando corresponda.

2023-01-22 20:39 UTC, dherranz1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/presentation/NewsFeedViewHolder.kt
> +            binding.descriptionNews.visibility = View.GONE
Esto lo quité porque tiene un fallo de visualización que no he logrado hasta ahora solventar, no sé si habrá alguna solución sencilla pero hasta ahora por todo lo que he investigado creo que la solución es definir transiciones más elaboradas. En esencia el error que se produce en la animación es que se actualiza la altura antes de realizar la animación, esto hace que el item inferior se monte sobre el item que está colapsando antes de finalizar la animación. En resumen, no sigue al elemento superior según se va animando.

2023-01-22 23:48 UTC, dherranz1 commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/presentation/NewsFeedViewModel.kt
> +        val newsFeed: Either<ErrorApp, List<GetNewsUseCase.NewFeed>>? = null
@josem-perram Ya he probado a implementar lo que comentas con el nuevo modelo, lo vemos en clase y si me das el visto bueno hago el cambio definitivo y la PR

El naming tenía pensado luego hacer un refactor y agregar la s, tuve el descuido al principio y para poder probar el código y no generar conflictos pues lo he ido arrastrando...

2023-01-24 10:52 UTC, josem-perram requested changes
Please, revisa los comentarios.

2023-01-24 10:52 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/presentation/NewsFeedViewModel.kt
> +        newsPublisher.value = NewsUiState()
Aquí es mucho mejor indicar que estados necesitamos en este momento. Es mejor dejar los estados "apagados" y luego "activarlos" cuando se use. Fíjate:
`` newsPublisher.value = NewsUiState() ``
o
``newsPublisher.value = NewsUiState(isLoading = true)``

¿Qué queda más claro? No se a ti, pero yo he tenido que ir a la clase para saber porque no habías puesto el loading a true. En la segunda forma, se "lee" mejor. Cuando programamos leemos más código que escribimos, debemos hacer código para que se lea bien.

2023-01-24 10:52 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/domain/GetNewsUseCase.kt
>  class GetNewsUseCase @Inject constructor(private val repository: NewsRepository) {
Aprovecha esta PR para cambiar lo de 
``if(result.isLeft())
            ErrorApp.DataError().left()
        else``
 Ya que no debemos mapear el error, sólo el right para hacer el map, esto mismo es lo que hacemos en el repositorio, no mapear el error.

2023-01-24 10:52 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/presentation/NewsFeedViewHolder.kt
> +        setExpandsUI(news,description,binding.newsCardView)
no deberíamos añadir animaciones cuando no se produce un evento (onclick) sobre el item. El elemento ya debería mostrarse expandido o colapsado según su estado anterior.

2023-01-24 10:52 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/presentation/NewsFeedViewModel.kt
> +        val newsFeed: Either<ErrorApp, List<NewsUi>>? = null
Daniel, aquí te falta un estado más, el val error: ErrorApp ? = null que almacenará el error cuando el caso de uso nos devuelva left y estará a null cuando el caso de uso nos devuelve right. Esto lo explicamos en la parte del detalle de SuperHeroes:
![image](https://user-images.githubusercontent.com/93087250/214272466-ded22c86-5e6d-4453-b138-ee516e6b1a0c.png)

2023-01-24 10:52 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/presentation/NewsFragment.kt
> +                    if(newsFeed == null || newsFeed.isLeft())
esto no haría falta cuando metas el estado del error.

2023-01-24 10:52 UTC, josem-perram commented on app/src/main/res/layout/news_item.xml
> +            <TextView
Recuerda extender del TextView de Material.

2023-01-24 10:52 UTC, josem-perram commented on app/src/main/res/layout/news_item.xml
> +    android:layout_height="wrap_content"
Los estilos van de colores, tamaños, etc. Los margenes de los elementos si deben estar aplicados.

2023-01-24 10:52 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/presentation/adapter/NewsFeedAdapter.kt
> +    private val listDifferCallback = object : DiffUtil.ItemCallback<NewsFeedViewModel.NewsUi>(){
Muy bien, esto es justo lo que pedía. Lo has conseguido por tus propios médios.

2023-01-25 14:58 UTC, RafaX8 commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/presentation/NewsFragment.kt
> +    private fun setupView(view : View){
Veo que mandas un view por parámetro y que no utilizas en la función. Dime si me he saltado algo 😅

2023-01-25 15:10 UTC, RafaX8 commented on app/src/main/res/values/dimens.xml
> +</resources>
Hemos añadido genéricos que puedes usar, pero si estás más cómodo con estos personalizados, perfecto.

2023-01-25 15:15 UTC, RafaX8 reviewed
Sé que aún hay cosas que cambiar, así que de momento no doy approve, pero va bien 👍 
![image](https://user-images.githubusercontent.com/104196849/214601014-a1bb4303-95f7-4e5f-9c81-7ddee9478069.png)

2023-01-26 00:05 UTC, josem-perram requested changes
Please, revisa los comentarios.

2023-01-26 00:05 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/news/presentation/NewsFragment.kt
> +        showErrorMessage(getString(R.string.error_data))
Esto no hacía falta hacerlo, creo que en el ticket se mencionaba poner un ToDo. Déjalo como está pero este código debe ser reemplazado por una clase que se encargue de gestionar los errores y sea común a todo el proyecto.

2023-01-26 00:05 UTC, josem-perram commented on app/src/main/res/values/dimens.xml
> +</resources>
Debe usar los genéricos, asi es como se menciona en el ticket y creo que eso ya lo habíamos comentado. Lo puso Joel en el canal de slack.

2023-01-26 07:41 UTC, dherranz1 commented on app/src/main/res/values/dimens.xml
> +</resources>
Cambiado

2023-01-26 19:16 UTC, josem-perram submitted a review, later dismissed
🚀

2023-01-26 19:18 UTC, josem-perram approved these changes

2023-01-27 14:33 UTC, RafaX8 approved these changes
Veo que va por buen camino, discúlpame los cambios que has tenido que hacer en mis archivos.
![image](https://user-images.githubusercontent.com/104196849/215111642-1ef6c2da-8be3-4562-b909-c7ca9d4bd52f.png)

2023-01-27 16:12 UTC, merged