Listado de adopciones (presentación)
iesalonsodemadrigal/android-huellas pull request #34
Opened 2023-01-25 16:00 UTC by RafaX8

## Descripción de la tarea
Se desea visualizar el listado de animales disponible para adoptar. Este listado de animales se mostrará cuando el usuario pulse sobre el botón del menú principal: Adopciones.

El fragmento debe tener una toolbar con el título: Adopciones. Esta toolbar debe tener el estilo genérico de toolbar de la app: SectionToolbarStyle. Los parámetros del estilo lo subirá Chema en una PR. No debe llevar botones, se hará en siguientes PR.

La vista tendrá tres estados:

1. Estado de carga: Es el estado que se muestra cuando se van a buscar datos.
2. Estado con datos: Es la visualización de la información obtenida del dominio.
3. Estado con error: Es el estado que muestra una pantalla de error cuando dominio nos devuelve un error.

Para el estado de error, mostraremos una pantalla de error. Esta pantalla se pondrá por encima de la pantalla de estado con datos. Esta pantalla será propuesta en otro ticket, mientras se dejará con un //TODO este estado.

Además, cuando el usuario haga tap sobre uno de los animales a adoptar, debería navegar a otro fragmentos (detalle del animal a adoptar). Este es el único evento asociado al ticket.

## ¿Cómo se ha implementado?
Principalmente se ha desarrollado la estructura de archivos de presentation.

1. Presentation
- AdoptionsFeedFragment:
Es el fragmento donde se muestra el recyclerView de animales en adopción. Es una lista normal y corriente a la que se le han añadido Skeleton para el estado de carga de los items y, en la función setupObservers, se ha realizado una comprobación de errores. En caso de recibir dicho error navega a otro fragmento aún por implementar (ErrorFragment)
- AdoptionsFeedViewModel:
ViewModel del que se obtiene la lista de animales. Aquí se trata el error en primera instancia, cambiando el estado de una data class (UiState) en función de lo recibido por el UseCase.

2. Presentation > adapter
- AdoptionFeedViewHolder:
Aquí se trata la información recibida de cada animal. Se añade el SetOnClickListener para abrir el detalle del animal en al pinchar. De momento, la única comprobación hecha aquí es la fecha de nacimiento.

- AdoptionsFeedAdapter:
Adapter del recyclerView. Se ha implementado diffUtil para el refresco de la lista y el ItemClick.

> Estilos aún por implementar.

## Keywords
Vistas, Presentation, RecyclerView.

## Screenshots or Video
TODO

2023-01-26 00:17 UTC, josem-perram requested changes
Rafa revisa los comentarios y sugerencias.

2023-01-26 00:17 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/presentation/AdoptionsFeedFragment.kt
> +            AdoptionsFeedFragmentDirections.actionToAdoptionsError()
De momento valía con un ToDo, así se comentaba en el ticket. La idea de la gestión de errores, es crear una clase genérica como la que has hecho para toda la app. Déjalo así y cuando cree el ticket de los errores comentamos el fragmento que has hecho.

2023-01-26 00:17 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/presentation/AdoptionsFeedViewModel.kt
> +        val isError: ErrorApp? = null,
esto no afecta a la funcionalidad pero el naming es un poco confuso. Cuando usamos isXXXX esperamo un booleano. Yo mi consejo es poner simplemente error.

2023-01-26 00:17 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/presentation/adapter/AdoptionsFeedAdapter.kt
> +    private val differCallback = object : DiffUtil.ItemCallback<Animal>() {
@RafaX8 te doy mi propuesta sobre el DiffUtil. Para usar esta clase de una forma más sencilla, existe un adaptador llamado ListAdapter. El código quedaría así:

```
class AdoptionsFeedAdapter @Inject constructor() :
    ListAdapter<Animal, AdoptionsFeedViewHolder>(AsyncDifferConfig.Builder(AnimalDiff()).build()) {

    private var itemClick: ((Int) -> Unit)? = null

    fun setOnClickItem(itemClick: (Int) -> Unit) {
        this.itemClick = itemClick
    }

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): AdoptionsFeedViewHolder{
        val view =
            LayoutInflater
                .from(parent.context)
                .inflate(R.layout.view_item_adoptions_feed, parent, false)
        return AdoptionsFeedViewHolder(view)
    }

    override fun onBindViewHolder(holder: AdoptionsFeedViewHolder, position: Int) {
        holder.bind(currentList[position], itemClick)
    }

    override fun getItemCount(): Int = currentList.size

}
```

Y el DiffUtil sería:

```
class AnimalDiff : DiffUtil.ItemCallback<Animal>() {

    override fun areItemsTheSame(oldItem: Animal, newItem: Animal): Boolean {
        return oldItem.id == newItem.id
    }

    override fun areContentsTheSame(oldItem: TapaFeedModel, newItem: TapaFeedModel): Boolean {
        return oldItem == newItem
    }
}
```

2023-01-26 00:17 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/presentation/adapter/AdoptionsFeedViewHolder.kt
> +        if(animal.date_born != ""){
Desde backend forzaremos que llegue siempre una fecha, aunque sea vacía.

2023-01-26 10:28 UTC, RafaX8 commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/presentation/AdoptionsFeedFragment.kt
> +            AdoptionsFeedFragmentDirections.actionToAdoptionsError()
Okay, pensé que había que dejar el TODO en el fragmento 😅

2023-01-26 10:28 UTC, RafaX8 commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/presentation/AdoptionsFeedViewModel.kt
> +        val isError: ErrorApp? = null,
lo cambiaré👍

2023-01-26 10:30 UTC, RafaX8 commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/presentation/adapter/AdoptionsFeedViewHolder.kt
> +        if(animal.date_born != ""){
okay 👌

2023-01-26 10:34 UTC, RafaX8 commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/presentation/adapter/AdoptionsFeedAdapter.kt
> +    private val differCallback = object : DiffUtil.ItemCallback<Animal>() {
Entiendo que de esta manera la clase del Adapter reduciría todo el código del diffutil para extraerlo a una clase aparte que sería AnimalDiff, y el adapter solo tendría que heredar también de ListAdapter 🤔 AnimalDiff se encontraría como una clase encapsulada dentro del adapter o se encontraría en un fichero separado?

2023-01-26 16:52 UTC, amrubio27 commented on app/src/main/java/com/iesam/proyecto_huellas/features/adopciones/presentation/AdoptionsFeedViewModel.kt
> +        val isError: ErrorApp? = null,
Me lo apunto. 👌

2023-01-26 17:02 UTC, amrubio27 commented
Buena PR rafa ✌. 
Me interesa tu PR para saber manejarme mejor con la parte de 'presentation' la verdad. Voy a ver lo que puedo aportar y lo que te puedo ver. _**Te comento si necesito que me expliques algo!**_ 

> Solo comentar que he hecho pequeños datos en el estilo visual de la misma para **enfatizar** lo que se quiere hacer, lo que se quiere cambiar y las anotaciones de la misma. Para facilitar la lectura vaya 🤣 
> 
> Recordad que tenéis arriba a la derecha del texto las herramientas para hacerlo. **Así se ve todo más rápido de un vistazo!!!**

2023-01-26 19:20 UTC, josem-perram submitted a review, later dismissed
👍

2023-01-27 11:47 UTC, dherranz1 submitted a review, later dismissed
:+1:

2023-01-27 15:39 UTC, amrubio27 submitted a review, later dismissed
👌

2023-01-27 16:02 UTC, dherranz1 submitted a review, later dismissed
:muscle:

2023-01-27 16:32 UTC, RafaX8 commented
@josem-perram No puedo hacer merge por unos conflictos, pero no acabo de entender por qué. Si puedes, agradecería que me ayudaras después por favor.  😅

2023-01-27 18:24 UTC, merged