share Intent
iesalonsodemadrigal/android-huellas pull request #36
Opened 2023-01-26 15:16 UTC by RafaX8

## Descripción de la tarea
Poder compartir adopciones entre amigos para fomentarlas. Para ello, facilitaremos el compartir dicha información.
Se pide añadir un botón de compartir en la card que me permita pasar un link de la web con la adopción a otras aplicaciones: whatsapp, email, etc.

## ¿Cómo se ha implementado?
Se ha implementado una función en archivo general nuevo: app > actions > Intents.kt.
A esta función se le manda el contexto del fragmento y en ella despliega un bottomsheet proporcionado por un Intent de AndroidStudio que permite compartir con otras apps.
Se han determinado los siguientes parámetros:
- action = Intent.ACTION_SEND --> Envía un único dato.
- type = "text/plain" --> El tipo de dato enviado es TEXTO PLANO. Se barajó la posibilidad de mostrar una imagen del animal compartido, pero se escapa de las exigencias del ticket y podría tornarse más complicado de lo necesario.
- putExtra(...) --> El mensaje que se muestra en el mensaje compartido.

En el fichero string.xml se ha añadido un string que recogerá la función share, de manera que no se ha hardcodeado el mensaje que se encía por Whatsapp, etc.

En el ViewHolder se ha añadido un Listener para el icono Share, de manera que ejecuta la función shareAnimals cuando es clicado.

## Keywords
Listener, Intent, share, ViewHolder, Strings, etc.

## Screenshots or Video

https://user-images.githubusercontent.com/104196849/214873281-8121a02c-1959-4a16-a85b-bd696c4b676d.mp4

2023-01-26 15:57 UTC, DavidCaidas submitted a review, later dismissed
![image](https://user-images.githubusercontent.com/104197044/214883985-5417a28a-bcd2-40e7-a37d-314e0f9487a8.png)
se ve fino mirmano, no he visto ningun fallo
pero tampoco entiendo mucho el codigo de la funcion share
![image](https://user-images.githubusercontent.com/104197044/214884293-fa918e98-24df-4515-aff6-285cb86ab17e.png)

me lo explicas en un miaumento ?

2023-01-26 16:02 UTC, DavidCaidas commented
ya lo entendí
gracias por la explicación
![image](https://user-images.githubusercontent.com/104197044/214885636-5a646437-e18f-4f2a-8638-a2374a4dc6f5.png)

2023-01-26 19:33 UTC, josem-perram requested changes
Hola Rafa, please, revisa los comentarios. Me interesa saber más sobre el paso de información entre aplicaciones, pensé que Dani tenía hecho algo común para toda la app. Una de las cosas que se debe pasar, es la URL de la donación. Por ejemplo, creo que vendría pasar el siguiente texto (se me acaba de ocurrir ahora, se aceptan propuestas):
```
¡Hola! Tobi está buscando familia, ¿te gustaría adoptarle? Puedes ver toda la información de Tobi en el siguiente enlace: https://www.protectorahuellas.org/adopcion-de-gatos/gatos-en-adopcion/item/6924-6924
```
Algo así.

2023-01-26 19:33 UTC, josem-perram commented on app/src/main/java/com/iesam/proyecto_huellas/app/actions/Intents.kt
> +fun shareAnimals(animal: Animal, context: Context){
Hola Rafa, creo que Daniel ya había creado una función genérica para compartir información a través de intent. Creo que se comparte el nombre y la url, tiene mucho sentido que se comparta la url del animal para quién reciba la información pueda hacer tap sobre el link y ver la ficha del animal.

2023-01-26 19:33 UTC, josem-perram commented on app/src/main/res/values/strings.xml
> +    <string name="adoptions_share_text">Adopta a </string>
Aquí es mejor que pases parámetros a la cadena xml. Esto se hace así:
```
<string name="adoptions_share_text">Adopta a %1$s</string>
```
El 1 viene de que es el primer parámetros, si tenemos que pasar más parámetros serían %1$s %2$s, etc.
la letra s detrás de $ es que se va a recibir un string. Si es un entero se pone la letra d, ejemplo: %1$d

Para pasar el parámetro sería:
```
context.getString(R.string.adoptions_share_text, animal.name)
```

2023-01-27 15:04 UTC, RafaX8 commented on app/src/main/res/values/strings.xml
> +    <string name="adoptions_share_text">Adopta a </string>
Muy interesante esto, lo añadiré en el siguiente commit

2023-01-27 19:22 UTC, RafaX8 commented
## UPDATE
Se ha añadido una función para el share genérica creada por @dherranz1 . Al clicar se llama a esa función y se le envía por parámetro el título y el contenido. Ambas dos se encuentran de forma predeterminada en strings, y se ha implementado el paso por parámetros a esas cadenas con el formato %1$s, %2$s.

TODO: la segunda cadena debería ser la URL de la protectora. A falta de ella, se ha puesto la URL a la imagen de prueba para comprobar si se mostraba como se esperaba en el diseño.

## Screenshots
![image](https://user-images.githubusercontent.com/104196849/215178932-21ed56df-f8a3-41d8-8fd8-8fef3a8ee4c4.png)

2023-01-27 19:40 UTC, dherranz1 commented
@RafaX8 Para compartir información hay muchas opciones interesantes en la documentación oficial, en un primer momento se comentó que únicamente se iba a compartir un enlace, no obstante veo muy interesante la opción de pasar una imagen también, además viene detallado en la propia documentación si no recuerdo mal. Posteriormente se puede valorar mejorarlo si sobra tiempo.

```
 val share = Intent.createChooser(Intent().apply {
      action = Intent.ACTION_SEND
      putExtra(Intent.EXTRA_TEXT, "https://developer.android.com/training/sharing/")

      // (Optional) Here setting the title of the content
      putExtra(Intent.EXTRA_TITLE, "Introducing content previews")

      // (Optional) Here passing a content URI to an image to be displayed
      data = contentUri
      flags = Intent.FLAG_GRANT_READ_URI_PERMISSION
  }, null)
  startActivity(share)

```

Se puede ver el punto opcional dos, donde explica cómo meter una imagen, pero no lo he probado. Lo omití porque en principio no era necesario pero se puede probar.

2023-01-28 22:07 UTC, alonsogallego7 submitted a review, later dismissed
Perfecto 👌

2023-01-30 23:26 UTC, josem-perram approved these changes
👍

2023-01-31 10:59 UTC, RafaX8 commented
Os tengo que pedir review una vez más para hacer el merge a Develop 😅 @josem-perram  @DavidCaidas  @alonsogallego7

2023-01-31 11:12 UTC, alonsogallego7 approved these changes

2023-01-31 13:53 UTC, josem-perram approved these changes
A por ello!

2023-01-31 14:23 UTC, merged